spring:
  application:
    name: rule-engine
  rabbitmq:
    host: "${RABBIT_HOST:localhost}"
    port: "${RABBIT_PORT:5672}"
    username: "${RABBIT_USER:guest}"
    password: "${RABBIT_PASSWORD:guest}"

server:
  port: "${PORT:8020}"

engine:
  config_file: "${CONFIG_DIR:src/main/resources/rule_engine_config.xml}"
  pattern-file: "${PATTERN_DIR:/app/report_service/patterns/patterns.json}"

