version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    # image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname:  'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s  # Check every 5 seconds
      timeout: 10s  # Wait up to 10 seconds for response
      retries: 5     # Retry up to 5 times
    networks:
        - application

  rabbitmq_init:
    build: 
      context: .
      dockerfile: rabbitDockerfile
    depends_on:
      - rabbitmq
    networks:
        - application

networks:
  application:
    driver: bridge